"""Add venue reviews

Revision ID: c7309f9d6890
Revises: 001_initial
Create Date: 2026-04-22 10:52:52.174355+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7309f9d6890'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='uq_user_venue_review')
    )
    op.create_index(op.f('ix_venue_reviews_user_id'), 'venue_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_venue_reviews_venue_id'), 'venue_reviews', ['venue_id'], unique=False)
    
    # Add columns with server_default for existing rows
    op.add_column('venues', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False, server_default='0.0'))
    op.add_column('venues', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'review_count')
    op.drop_column('venues', 'rating')
    op.drop_index(op.f('ix_venue_reviews_venue_id'), table_name='venue_reviews')
    op.drop_index(op.f('ix_venue_reviews_user_id'), table_name='venue_reviews')
    op.drop_table('venue_reviews')
    # ### end Alembic commands ###
