"""Add courts and booking slots

Revision ID: 58a981ca9001
Revises: bb7e2bad3417
Create Date: 2026-04-23 09:24:15.362876+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a981ca9001'
down_revision: Union[str, None] = 'bb7e2bad3417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_deleted_at'), 'courts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_courts_venue_id'), 'courts', ['venue_id'], unique=False)
    op.create_table('booking_slots',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_slots_booking_id'), 'booking_slots', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_slots_court_id'), 'booking_slots', ['court_id'], unique=False)
    op.create_index(op.f('ix_booking_slots_deleted_at'), 'booking_slots', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_slots_deleted_at'), table_name='booking_slots')
    op.drop_index(op.f('ix_booking_slots_court_id'), table_name='booking_slots')
    op.drop_index(op.f('ix_booking_slots_booking_id'), table_name='booking_slots')
    op.drop_table('booking_slots')
    op.drop_index(op.f('ix_courts_venue_id'), table_name='courts')
    op.drop_index(op.f('ix_courts_deleted_at'), table_name='courts')
    op.drop_table('courts')
    # ### end Alembic commands ###
