"""refactor_pricing_to_absolute_amounts

Revision ID: db46c628336e
Revises: 20260423_1200
Create Date: 2026-04-24 00:44:09.777092+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db46c628336e'
down_revision: Union[str, None] = '20260423_1200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_profile_slots', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('pricing_profile_slots', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('pricing_profile_slots', 'price_factor')
    op.add_column('pricing_time_slots', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('pricing_time_slots', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('pricing_time_slots', 'price_factor')
    op.alter_column('venues', 'base_price_per_hour',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'base_price_per_hour',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.add_column('pricing_time_slots', sa.Column('price_factor', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.drop_column('pricing_time_slots', 'is_default')
    op.drop_column('pricing_time_slots', 'price')
    op.add_column('pricing_profile_slots', sa.Column('price_factor', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.drop_column('pricing_profile_slots', 'is_default')
    op.drop_column('pricing_profile_slots', 'price')
    # ### end Alembic commands ###
