"""Refactor multi court booking

Revision ID: bb7e2bad3417
Revises: c7309f9d6890
Create Date: 2026-04-22 19:20:09.407821+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb7e2bad3417'
down_revision: Union[str, None] = 'c7309f9d6890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'service_fee')
    op.drop_column('bookings', 'price_factor')
    op.drop_column('bookings', 'start_time')
    op.drop_column('bookings', 'duration_minutes')
    op.drop_column('bookings', 'base_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('price_factor', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('service_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
